### ISSUE TITLE
waitlist module working?

### ISSUE THREAD

**Issue by likewhoa** [NYC-Camp/website#274]
Did anyone test this? I tried to enable waitlist on a node and it doesn't seem to take effect. Also, what's the point of leaving it checked on admin/structure/registration/registration_states

**Comment by ForestMars** [comment]
It's unclear to me if this is working for normal users. 

It seems to work for admin, though the UI seems buggy, however my sense is that Entity Regitration's wait list functionality is not working on the NYC Camp site.  

I took a look at the issue queue for Wait list, and it seems like it should be working, although I got the sense there may be some brittleness to it (also a fair number of issues where people were not cleanly testing it as user/1 vs. testing as unprivileged auth user.)

So I would file this under 'presumed not to work until proven otherwise.'

**Comment by likewhoa** [comment]
yea, i tried to test with a normal user and it's not showing up so it seems to not be working. We also should uncheck the 'state' in admin/structure/registration/registration_states as this shows up for all site-admins on every registration form and it's confusing.

**Comment by likewhoa** [comment]
P.S i enabled waitlist for http://www.nyccamp.org/2014/trainings/decision-makers since it was the first event i saw that had all slots taken up and didn't have wait list enabled, but authenticated users still see 'Sorry, registrations are no longer available for Decision Makers' on it even after clearing cache (just to test).

**Comment by ForestMars** [comment]
Given that the module's issue queue seems to indicate it is working, what might be have done to break it?

**Comment by likewhoa** [comment]
@ForestMars dunno but I will troubleshoot this later tonight.

**Comment by likewhoa** [comment]
https://drupal.org/node/2231097 for reference on this as currently waitlist is not functioning.

**Comment by ForestMars** [comment]
yes, I don't think that issue (which I filed) is necessarily related. In fact I closed it as it seems like it's just ui/configuration for user/1. 

Nothing in there seemed to fix Wait list on the nyccamp site, and I haven't had a chance to spin up a clean D7 sandbox to confirm that wait list works out of the box.
