### ISSUE TITLE
Planet feed completely broken

### ISSUE THREAD

**Issue by ForestMars** [NYC-Camp/website#288]
What happened here? 

Drupal planet feed is completely broken on the new site. It's working perfectly on last year's site just the way I set it up, but this year's site doesn't even have the taxonomy term. Who deleted that? 

Moreoever, we need to get this fixed. I'm marking this as a critical issue since we can't publish our post-camp news until it's fixed and that was supposed to go out first thing tomorrow morning.

**Comment by ForestMars** [comment]
Update: Someone changed the Drupal Planet taxonomy term to "Walking with Shawn on the Beach."

How in the world did that happen?

**Comment by ForestMars** [comment]
Fixed, but how in the world did that happen. 

Also @likewhoa why is the filter set to "published or admin" and not just published?

**Comment by likewhoa** [comment]
@ForestMars probably a mistake on my part but shouldn't cause the feed to not show. I would like to know who when ahead and renamed that term ffs.

**Comment by ForestMars** [comment]
Why in the world would you close this issue? Our planet feed is completely broken and we cannot publish our post-camp news since this morning (actually since yesterday.) 

Please do not close this issue until it's actually fixed, tested and our planet feed is showing up on drupal.org

**Comment by likewhoa** [comment]
closed \o/ I didn't know that feed was still showing duplicates. All good now.

**Comment by willykaram** [comment]
I'm going to post an update to the issue here to try and help use resolve this.

We should be constructing the the view with fields as opposed to using display suite, since that provides us with the fields settings needed for the RSS.

As opposed to mixing the news/RSS views, we should have the view for the RSS feed in it's own view for two reasons: 
1. The Drupal Planet feed/view is very important, as it's broadcasting our content out to the entire world on g.d.o., and over time may involve content other than just news posts. Additionally the structure of the /news view is going to be different and involve more fields than the planet feed.
2. Other camps may or may note need this planet/feed feature, so it's beneficial to have it in a separate view so that it can be enabled/disable.

This is a recap of what Forest and I discussed earlier this evening.

**Comment by likewhoa** [comment]
very good points @willykaram and with that I agree to keep it separate, but how is DS being used here since we are using normal drupal displays?

**Comment by willykaram** [comment]
We were using content display on the old view,  was being used in the old view that you deleted (you can tell by the machine name).

**Comment by willykaram** [comment]
We should have excluded the old posts from this view so that they didn't go out on planet.

**Comment by likewhoa** [comment]
yes content display doesn't mean we are using display suite. drupal comes with an RSS display by default. DS is not a problem here.

**Comment by likewhoa** [comment]
Our feed shouldn't be so populated as you have it now,.. it should be straight forward with just title,post date,image & body. Our node display can show the rest of the fields. lets keep it simple.

**Comment by ForestMars** [comment]
krect, the planet rss feed has only those 4 fields. 

do what you like with the node (full), use ds if you like!

**Comment by likewhoa** [comment]
ok, nothing to see here folks. All good. willyk++ kombucha++ rule32++

**Comment by willykaram** [comment]
The feed now looks good on g.d.o: https://drupal.org/aggregator/sources/1319

Hopefully we can get the post about Holly published this morning and onto Planet.

**Comment by ForestMars** [comment]
Fixed and it looks great on planet-- Thanks to everyone!
